# Generated by Django 3.1.10 on 2021-05-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0019_auto_20210508_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='title_ru',
            field=models.CharField(default='имя покемона', max_length=200),
        ),
    ]
